### 1) Develop a python program to read n digit integer number and seperate the integer number and display each digit

In [10]:
n=int(input("enter the number of digits:"))
if n>0:
    number=int(input(f"enter {n}-digit integer"))
    if number>=10**(n-1)and number<10**n:
        for i in range(n):
            digit=number//(10**(n-1))
            print(digit)
            number%=10**(n-1)
            n-=1
    else:
        print(f"please enter a {n}-digit integer")
else:
    print(f"please enter a valid number of digits(greater than 0)" )

enter the number of digits:3
enter 3-digit integer123
1
2
3


### 2). Develop a python program to accept 4 numbers an display them in sorted order using a minimum number of if-else statement

In [9]:
a=int(input("enter the first number"))
b=int(input("enter the second number"))
c=int(input("enter the third number"))
d=int(input("enter the fourth number"))
if a>b:a,b=b,a
if c>d:c,d=d,c 
if a>c:a,c=c,a
if b>d:b,d=d,b
if b>c:b,c=c,b
print("the sorted numbers are:",a,b,c,d)
    

enter the first number4
enter the second number3
enter the third number7
enter the fourth number1
the sorted numbers are: 1 3 4 7


## Find the bitwise AND of 10 and 9

In [10]:
a=10&9
print(a)

8


## Find the bitwise OR of 10 and 9

In [12]:
a=10|9
print(a)

11


## Find the bitwise NOT of 10 and 9

In [13]:
a=~10
print(a)

-11


## Find the bitwise XOR of 10 and 9

In [1]:
a=-12
b=a>>2
print(b)


-3


In [4]:
bin(1)

'0b1'

In [20]:
a=3
b=2
a is b

False

### 3) develop a program for checking if a given n digit number is palindrome or not .

In [12]:
num=int(input("Enter an n-digit number:"))
origin_num=num
rev_num=0
while num>0:
    digit=num%10
    rev_num=rev_num*10+digit
    num//=10
if origin_num==rev_num:
    print("palindrome")
else:
    print("Not a palindrome")

Enter an n-digit number:121
palindrome


### 4) Develop a python script to display a multiplication table for given integer n.

In [13]:
n=int(input("Enter an integer for the multiplication table:"))
print(f"Multiplication Table for {n}:")
for i in range (1,11):
    result=n*i;
    print(f"{n}x{i}={result}")

Enter an integer for the multiplication table:-3
Multiplication Table for -3:
-3x1=-3
-3x2=-6
-3x3=-9
-3x4=-12
-3x5=-15
-3x6=-18
-3x7=-21
-3x8=-24
-3x9=-27
-3x10=-30


In [14]:
t1=7
t2=8
t1 is t2

False

In [17]:
print("I am","from","India",sep=",")

I am,from,India


### 5) Develop a python scripts to calculate the mean,median,mode,variance and S.D of n integer number

In [1]:
n=int(input("Enter5 the number of elements"))
num=[int(input(f"Enter number {i+1}:")) for i in range(n)]
mean=sum(num)/n
num.sort()
if n%2==0:
    median=(num[n//2-1]+num[n//2])/2
else:
    median=num[n//2]
frequency={nums:num.count(nums) for nums in num}
max_count=max(frequency.values())
mode=[k for k,v in frequency.items() if v==max_count]
if len(mode)==n:
    mode="Nomode"
mean_dif_squ_sum=sum((x-mean)**2 for x in num)
var_sam=mean_dif_squ_sum/(n-1) if n>1 else 0
var_pop=mean_dif_squ_sum/n
std_div_sam=var_sam**0.5
std_div_pop=var_pop**0.5
print(f"mean={mean}")
print(f"median={median}")
print(f"mode={mode}")
print(f"sample variance={var_sam}")
print(f"population variance={var_pop}")
print(f"sample standard deviation={std_div_sam}")
print(f"population standard deviation={std_div_pop}")

Enter5 the number of elements6
Enter number 1:4
Enter number 2:8
Enter number 3:6
Enter number 4:5
Enter number 5:3
Enter number 6:9
mean=5.833333333333333
median=5.5
mode=Nomode
sample variance=5.366666666666667
population variance=4.472222222222222
sample standard deviation=2.316606713852541
population standard deviation=2.1147629234082532


### 6) develop a python program to read to rotate right abouyt a given position in that list and display them[hint: input[1,4,5,-10] position:2 output[-10,5,4,1]

In [2]:
number=int(input("enter the integer number:"))
revs_number=0
while(number>0):
    remainder=number%10
    revs_number=((revs_number)*10)+remainder
    number=number//10
print("the reverse number is:{}".format(revs_number))

enter the integer number:253
the reverse number is:352


 ### 7) develop or write a python program to interchange the digits integer number[hint,input:23456,interchange:3&5, output:2 5 4 3 6]

In [3]:
def interchange_digits(number,pos1,pos2):
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int("".join(number_list))
    return interchanged_number
number=int(input("enter the user input"))
pos1=int(input("enter the first position which you want to swap:"))
pos2=int(input("enter the second position which you want to swap:"))
interchanged_number=interchange_digits(number,pos1,pos2)
print("original number:",number)
print("interchanged number:",interchanged_number)    

enter the user input12345
enter the first position which you want to swap:1
enter the second position which you want to swap:2
original number: 12345
interchanged number: 21345


### 8) Develop a python to capitalize a given list.

In [1]:
def capitalize_string(string_list):
    return [s.capitalize() for s in string_list]
input_string=['hello','good','how','simple']
capitalized_string=capitalize_string(input_string)
print(capitalized_string)

['Hello', 'Good', 'How', 'Simple']


### 9) Using a dictionary develop a python program to determine and print the no of duplicate words in a sentence.

In [3]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={}
    for word in words:
        word =word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
    duplicate={word:count for word,count in word_count.items() if count>1}
    if duplicate:
        print("duplicate words &their counts:")
        for word,count in duplicate.items():
            print(f"{word}:{count}")
    else:
            print("no duplicate word is found")
sentence=input("enter a sentence ")
count_duplicate_words(sentence)

enter a sentence hi hello hi hello
duplicate words &their counts:
hi:2
hello:2


### 10) Develop a python program to read Numpy array and print row(sum,mean,std) and column(sum,mean,std)


In [5]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("Numpy array")
print(data)
print("---------------")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("Row sum")
print(totalr)
print("Column sum")
print(totalc)
print("---------------")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("Row mean")
print(meanr)
print("Column mean")
print(meanc)
print("---------------")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("Row STD")
print(stdr)
print("column STD")
print(stdc)


Numpy array
[[1 2 3]
 [4 5 6]]
---------------
Row sum
[ 6 15]
Column sum
[5 7 9]
---------------
Row mean
[2. 5.]
Column mean
[2.5 3.5 4.5]
---------------
Row STD
[0.81649658 0.81649658]
column STD
[1.5 1.5 1.5]


### 11) Develop a python program to read and print in the console

In [1]:
import csv
file=open('4vp23ai013.csv',mode='r')
csv_reader=csv.reader(file,delimiter=',')
line_count=0
for row in csv_reader:
    if line_count==0:
        print(f'column names are{",".join(row)}')
        line_count+=1
    else:
        print(f'\t{row[0]} works in the {row[1]} department, and was born in {row[2]}.')
        line_count+=1
print(f'Processed{line_count} lines.')
file.close()

column names arename,department,birthday_month
	John Smith works in the Accounting department, and was born in november.
	Erica Meyers works in the IT department, and was born in March.
	Rocky works in the HR department, and was born in april.
Processed4 lines.


In [8]:
import numpy as np
a=np.arange(4)
b=np.arange(5)
print(a)
a+=4
print(a)

[0 1 2 3]
[4 5 6 7]


### 12) develop a python pogram to read a HTML file with basic tag, and construct dictionary and display the same in the console

In [4]:
import pandas as pd 
def read_html_dict(html_file):
    tables=pd.read_html(html_file)
    tables_dict={}
    for i,table in enumerate(tables):
        table_dict=table.to_dict(orient='list')
        tables_dict[f'Table_{i+1}']
        return tables_dict
if__name_=='__main__':
    html_file='sample.html'
    result=read_html_to_dict(html_file)
    print(result)

SyntaxError: invalid syntax (2045457124.py, line 9)